config/routes.rb
Rails.application.routes.draw do
  resources :galleries
  devise_for :users
  devise_for :models
  root 'pages#home'

  get "contact" => "pages#contact"

  get "about" => "pages#about"

  get "policies" => "pages#policies"

  get "photographers" => "pages#photographers"

  get "badlandsphotos" => "pages#badlands"

  get "badlands/photos" => "pages#badlands"

  get "jobs" => "pages#jobs"

  get "stories" => "pages#stories"

  get "guides" => "pages#guides"

  get "discover" => "pages#discover"

  get "guideexample" => "pages#guideexample"

  get "badlands" => "pages#badlandsguide"

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	belongs_to :user

	has_many :images, class_name: 'GalleryImage', dependent: :destroy
	accepts_nested_attributes_for :images, :allow_destroy => true

 	 default_scope -> { order('created_at DESC') }
  	validates :user_id, presence: true

	has_attached_file :image, :styles => { :large => "800x600>", :medium => "300x300>", :thumb => "100x100>" }

	validates :title, presence: true

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	
end

app/models/gallery_image.rb
class GalleryImage < ActiveRecord::Base
  belongs_to :gallery

  validates :sequence_num, numericality: true
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :name, presence: true

  validates :username, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9]+\Z/ }
  before_save { |user| user.username = user.username.downcase }

  has_many :galleries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)
    @gallery.user = current_user
    if @gallery.save
      redirect_to @gallery
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    redirect_to galleries_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:title, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def contact
  end
  def about
  end
  def policies
  end
  def photographers
  end
  def jobs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/galleries/_form.html.erb
<%= form_for(@gallery, html: { class: 'gallery' }) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br>
  <div class="title">
  <div class="form-group" >
    <%= f.text_field :title, class: "form-control", placeholder: "Gallery Title" %>
  </div>
</div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control", placeholder: "Gallery Description" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<div class="body_squeeze">

  <h1>Listing galleries</h1>

  <table>
    <thead>
      <tr>
        <th>Image</th>
        <th>Description</th>
        <th>User</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @galleries.each do |gallery| %>
        <tr>
          <td><%= image_tag gallery.image.url(:medium) %></td>
          <td><%= gallery.description %></td>
          <td><%= gallery.user.email if gallery.user %></td>
          <td><%= link_to 'Show', gallery_path(gallery) %></td>
          <% if gallery.user == current_user %>
            <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
            <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <% if user_signed_in? %>
    <%= link_to 'New gallery', new_gallery_path %>
  <% end %>

</div>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @gallery.image.url %>

<p>
  <strong>Description:</strong>
  <%= @gallery.description %>
</p>

<!--%= link_to 'Edit', edit_galleries_path(@galleries) %> | -->
<!--%= link_to 'Back', galleries_path %> -->

app/views/layouts/_exclaimer.html.erb
<a class="fragment">
    <div class="fragment_message">Welcome! Please note that this is currently a work in progess. Check
      back for frequent updates!


<span id='close' onclick='this.parentNode.parentNode.parentNode.removeChild(this.parentNode.parentNode); return false;'>
  x</span>

</div>
</a>

app/views/layouts/_footer.html.erb
<div id="footer">
    <div class="foot_navs">
      <div class="foot_nav"><%= link_to "jobs", jobs_path %></div>
      <div class="foot_nav"><%= link_to "about", about_path %></div>
      <div class="foot_nav"><%= link_to "guides", guides_path %></div>
      <div class="foot_nav"><%= link_to "stories", stories_path %></div>
      <div class="foot_nav"><%= link_to "contact", contact_path %></a></div>
      <div class="foot_nav"><%= link_to "policies", policies_path %></div>
      <div class="foot_nav"><a href="#">blog</a></div>
      <div class="foot_nav"><a href="http://instagram.com/crotonwest">instagram</a></div>

    <div class="mailsqueeze">
    		<style type="text/css">
    			#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
    			/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
    			   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
    		</style>
    		<div id="mc_embed_signup">
    		<form action="//crotonwest.us11.list-manage.com/subscribe/post?u=d1c83cc613caa186ee5808046&amp;id=d138510d7f" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    		    <div id="mc_embed_signup_scroll">

    			<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email@example.com" required>
    		    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_d1c83cc613caa186ee5808046_d138510d7f" tabindex="-1" value=""></div>
    		    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    		    </div>
    		</form>
    		</div>
      </div>

app/views/layouts/_header.html.erb
<div id="navbar">
  <div class="navbar_squeeze">
      <div id="logo"><%= link_to "Croton West", root_path =%></div>

      <a href="#"><div class="navs">discover</div></a>
      <%= link_to stories_path do %><div class="navs">stories</div> <% end %>
      <%= link_to guides_path do %><div class="navs">guides</div> <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Croton West</title>
  <link href='https://fonts.googleapis.com/css?family=Raleway:200' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application','lightbox', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

 </head>

<body>
  <% if current_page?(root_path) %>
  	<%= render 'layouts/exclaimer' %>
    <% else %>
    <% end %>
 	<%= render 'layouts/header' %>
	<%= yield %>
	<%= render 'layouts/footer' %>

	<%= javascript_include_tag	'lightbox-plus-jquery' %>

  <!-- For Devise gem -->
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<script src="js/jquery.filterizr.min.js"></script>
</body>
</html>

app/views/pages/about.html.erb
<div class="pages_div">
  <div class="ninehundredpx">
    <div class="pages_title">About</div>
    <div class="pages_text">
    Croton West is a visual travel guide to North America's outdoor recreation areas.
<p></p>
  We photograph and document wildlife, landscapes, and adventure, for both art and science.
<p></p>
    We're based in New York and have photographers documenting the wild places all over.
<p></p>
    If you want to work with us, check out our <%= link_to "jobs", jobs_path %> page
  </div>
</div>
</div>

app/views/pages/badlandsguide.erb
<div class="guide_title_image">
  <div class="guide_title">Badlands National Park</div>
  <div class="guide_title_location">South Dakota, USA</div>
</div>

<div class="full_width_guide_nav">
  <div class="body_squeeze guide_links">

  <div class="guide_navbar">
    <a href="#photos"><div class="guide_nav">photos</div></a>
    <a href="#activities"><div class="guide_nav">activities</div></a>
    <a href="#camping_lodging"><div class="guide_nav">camping/lodging</div></a>
    <a href="#ecology"><div class="guide_nav">ecology</div></a>
    <a href="#maps"><div class="guide_nav">maps</div></a>
    <a href="#general_info"><div class="guide_nav">general info</div></a>

</div>

    <div class="guide_topic" id="photos">
      <br>

      <%= link_to "badlands/photos" do %><div class="photo_gallery_link">Photos</div><%end%>





    <div class="guide_topic_title" id="activities">Activities</div>


    <div class="guide_topic_subtitle">Hiking Trails</div>

<div id="accordion" role="tablist" aria-multiselectable="true">
    <a class="hikingtrail" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Door Trail <span class="mileage">0.75 miles/1.2 km</span>
    </a>
<br>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        Easy. An accessible ¼ mile boardwalk leads through a break in the Badlands Wall known as "the Door" and to a view of the Badlands. From there, the maintained trail ends. Travel beyond this point is at your own risk. Watch for drop-offs.
    </div>
    <a class="collapsed hikingtrail" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Window Trail <span class="mileage">0.25 miles/0.4 km</span>
    </a>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
        Easy. This short trail leads to a natural window in the Badlands Wall with a view of an intricately eroded canyon. Please stay on the trail.
    </div></div>
    <a class="collapsed hikingtrail" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Castle Trail <span class="mileage">10 miles/16 km </span>
    </a>
    <br>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
        Moderate. The longest trail in the park begins at the Door and Window parking area and travels five miles one way to the Fossil Exhibit Trail. Relatively level, the path passes along some badlands formations.
    </div>
    <a class="collapsed hikingtrail" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Cliff Shelf <span class="mileage">0.5 miles/0.8 km </span>
    </a><br>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
       Moderate. This loop trail follows boardwalks and climbs stairs through a juniper forest perched along the Badlands Wall. A small pond occasionally exists in the area and draws wildlife, such as deer or bighorn sheep. Climbs approximately 200 feet in elevation. Please stay on the trail.
    </div>
    <a class="collapsed hikingtrail" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
          Saddle Pass <span class="mileage">.25 miles/.40 km </span>
    </a><br>
    <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
    Strenuous. This short trail climbs up the Badlands Wall to a view over the White River Valley. The trail ends where it connects with the Castle and Medicine Root Loop Trails.
  </div>
    <a class="collapsed hikingtrail" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
          Medicine Root Loop <span class="mileage">  4 miles/6.4 km</span>
    </a><br>
    <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">

      Moderate. This generally rolling trail connects with the Castle Trail near the Old Northeast Road and at the intersection of the Castle and Saddle Pass Trails. Trail users are provided the opportunity to explore the mixed grass prairie while enjoying views of the Badlands in the distance. Watch for cactus.
    </div>
    <a class="collapsed hikingtrail" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
        Fossil Exhibit Trail <span class="mileage"> 0.25 miles/0.4 km</span>
    </a>
    <div id="collapseSeven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSeven">

      Easy. Fully accessible boardwalk trail features fossil replicas and exhibits of now extinct creatures that once roamed the area.
    </div>

<br><br>
    <img class="mapsize" src="<%= asset_path( 'badlandstrailmap.jpg' ) %>" />



    <br><br>



   <div class="guide_topic_subtitle">Backcountry</div><br>
Permits are not currently required for overnight stays in the Badlands backcountry. Backcountry registers are located at the Medicine/Castle Trail Loop, Saddle Pass Trailhead, Conata Picnic Area, Sage Creek Basin Overlook, and the Sage Creek Campground.
<br><br>
Since most backcountry trips are not on designated trails, topographic maps are strongly recommended. (Can be found in park store).
<br><br>
The park is home to many burrowing animals. Watch your footing.
<br><br>
Campfires are not permitted. Use a backpacking stove.
<br><br>
The location of your campsite must be at least 0.5 miles from a road or trail and must not be visible from a roadway.
<br><br>
There is no potable or filterable water in the backcountry. Always carry at least one gallon of water per person per day.
<br><br>
Keep an eye on weather. Severe thunderstorms are common during the summer, so are days above 100ºF (38ºC). September and early October are the best backpacking months.
<br><br>
Leave no trace

<br><br>
<div class="guide_topic_subtitle">Stargazing</div><br>


Summer night sky viewing is offered at the Cedar Pass Campground Amphitheater on Friday through Monday nights.
<br><br>

  </div>
  <div class="guide_topic" id="camping_lodging">
    <div class="guide_topic_title">Camping and lodging</div>

<div class="camp_image_text">

    <b>Cedar Pass Campground</b><br><br>
    Located near the Ben Reifel Visitor Center, the Cedar Pass Campground has 96 level sites with scenic views of the badlands formations.
    <br><br>
    Camping fees for up to two people are $22 per night per campsite, or $37 per night for campsites with electrical hook-ups. Each additional person is $4 per night. A dump station is available for a $1.00 per use fee. Cold running water, flush toilets, and covered picnic tables are available.
    <br><br>
    A limited section of the campground is open during the winter months.</p>
<hr>

    <b>Sage Creek Campground</b>
<br><br>
    Bison often wander through this primitive campground, located on the west side of the park's North Unit, near the Badlands Wilderness Area. Access is located off of the Sage Creek Rim Road, an unpaved road that may temporarily close after winter storms and spring rains. The road provides limited turnarounds for large recreational vehicles. Camping is free of charge. Pit toilets and covered picnic tables are available, but no water is available on-site. Sites at the Sage Creek Campground are available on a first-come, first-served basis and rarely fill to capacity. A portion of the Sage Creek Campground is designated for horse use.</p>
<hr>
    <p>Both campgrounds are open year-round, and camping is limited to 14 days. Due to fire danger, campfires are not permitted in either campground and collection of wood is prohibited.</p>
</div>
    <img class="portrait_image" src="<%= asset_path( 'badlandscamp.jpg' ) %>" />
    <br><br>


  </div>
  <div class="guide_topic" id="ecology">
    <div class="guide_topic_title">Ecology</div>
<img class="landscape_image" src="<%= asset_path( 'badlandseco.jpg' ) %>"/>
<div class="image_caption">A praire dog sits outside its hole on Sage Creek Rim Road</div>
<br>
    In Badlands National Park, scientists have observed 39 mammal species, 9 reptile species, 6 amphibian species, 206 bird species, and 69 butterfly species.
The prairie animals are well adapted to their environment. They can handle climate extremes and find protection in these vast, open spaces. Most small prairie mammals either dig burrows or invade another animal's burrow for shelter. Others hibernate or become dormant in the cold of the winter.


  <div class="guide_topic" id="maps">
    <div class="guide_topic_title">Map</div>
    <img class="mapsize" src="<%= asset_path( 'badlandsmap.jpg' ) %>" />
  </div>

  <div class="guide_topic" id="general_info">
    <div class="guide_topic_title">General info</div>
    <p>The park is open to visitors all year with the exception of weather closures.</p>

    <p>Private: Non Commercial Vehicle - $15.00
Fee covers the entry of a private non commercial vehicle and its occupants for 7 days.</p>

<p>25216 Ben Reifel Road
Interior, SD 57750 </p>




  </div>


<br>
<br>
<br>
<br>
</div>
</div>

app/views/pages/contact.html.erb
<head>
  <title>Contact - Croton West</title>
</head>
<body>

<div class="pages_div">
  <div class="ninehundredpx">
    <div class="pages_title">Contact</div>
For all general inquiries, email <a href="#">hello@crotonwest.com</a>
<br><br>
If you want to work with us, check out our <%= link_to "jobs", jobs_path %> page
  </div>
</div>
</body>
</html>

app/views/pages/discover.html.erb
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Filterizr Use Case</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>


    <div class="container">
        <!-- Filter Controls - Simple Mode -->
        <div class="row">
            <!-- A basic setup of simple mode filter controls, all you have to do is use data-filter="all"
            for an unfiltered gallery and then the values of your categories to filter between them -->
            <ul class="simplefilter">
                Simple filter controls:
                <li class="active" data-filter="all">All</li>
                <li data-filter="1">Cityscape</li>
                <li data-filter="2">Landscape</li>
                <li data-filter="3">Industrial</li>
                <li data-filter="4">Daylight</li>
                <li data-filter="5">Nightscape</li>
            </ul>
        </div>

        <!-- Filter Controls - Multifilter Mode -->
        <div class="row">
            <!-- A basic setup of multifilter controls, when the user toggles a category
            the corresponding items are rendered or hidden -->
            <ul class="multifilter">
                Multifilter controls:
                <li data-multifilter="1">Cityscape</li>
                <li data-multifilter="2">Landscape</li>
                <li data-multifilter="3">Industrial</li>
            </ul>
        </div>

        <!-- Shuffle & Sort Controls -->
        <div class="row">
            <ul class="sortandshuffle">
                Sort &amp; Shuffle controls:
                <!-- Basic shuffle control -->
                <li class="shuffle-btn" data-shuffle>Shuffle</li>
                <!-- Basic sort controls consisting of asc/desc button and a select -->
                <li class="sort-btn active" data-sortAsc>Asc</li>
                <li class="sort-btn" data-sortDesc>Desc</li>
                <select data-sortOrder>
                    <option value="domIndex">
                        Position
                    </option>
                    <option value="sortData">
                        Description
                    </option>
                </select>
            </ul>
        </div>

        <!-- Search control -->
        <div class="row search-row">
            Search control:
            <input type="text" class="filtr-search" name="filtr-search" data-search>
        </div>

        <div class="row">
            <!-- This is the set up of a basic gallery, your items must have the categories they belong to in a data-category
            attribute, which starts from the value 1 and goes up from there -->
            <div class="filtr-container">
                <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="1, 5" data-sort="Busy streets">
                    <img class="img-responsive" src="img/city_1.jpg" alt="sample image">
                    <span class="item-desc">Busy Streets</span>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="2, 5" data-sort="Luminous night">
                    <img class="img-responsive" src="img/nature_2.jpg" alt="sample image">
                    <span class="item-desc">Luminous night</span>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="1, 4" data-sort="City wonders">
                    <img class="img-responsive" src="img/city_3.jpg" alt="sample image">
                    <span class="item-desc">city wonders</span>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="3" data-sort="In production">
                    <img class="img-responsive" src="img/industrial_1.jpg" alt="sample image">
                    <span class="item-desc">in production</span>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="3, 4" data-sort="Industrial site">
                    <img class="img-responsive" src="img/industrial_2.jpg" alt="sample image">
                    <span class="item-desc">industrial site</span>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="2, 4" data-sort="Peaceful lake">
                    <img class="img-responsive" src="img/nature_1.jpg" alt="sample image">
                    <span class="item-desc">peaceful lake</span>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="1, 5" data-sort="City lights">
                    <img class="img-responsive" src="img/city_2.jpg" alt="sample image">
                    <span class="item-desc">city lights</span>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="2, 4" data-sort="Dreamhouse">
                    <img class="img-responsive" src="img/nature_3.jpg" alt="sample image">
                    <span class="item-desc">dreamhouse</span>
                </div>
                <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="3" data-sort="Restless machines">
                    <img class="img-responsive" src="img/industrial_3.jpg" alt="sample image">
                    <span class="item-desc">restless machines</span>
                </div>
            </div>
        </div>
    </div>

    <!-- Include jQuery & Filterizr -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="filterizr/jquery.filterizr.js"></script>
    <script src="js/controls.js"></script>

    <!-- Kick off Filterizr -->
    <script type="text/javascript">
        $(function() {
            //Initialize filterizr with default options
            $('.filtr-container').filterizr();
        });
    </script>

app/views/pages/guides.html.erb
<div class="body_squeeze">

<div class="story_pages_title">Guides</div>

<a class="story_link", href="#"><div class="story">
  Guide
</div></a>

<a class="story_link", href="#"><div class="story">
  Guide
</div></a>

<a class="story_link", href="#"><div class="story">
  Guide
</div></a>


</div>

app/views/pages/home_temp.html.erb
<head>
  <title>Croton West</title>
</head>
<body>
  <div class="main_div">


    <div id="banner">Exploring, discovering, and photographing North America</div>

    <div class="map">
      <iframe src="http://createaclickablemap.com/map.php?id=44640&online=true" width="900" height="525" style="border: none;"></iframe>
<script>if (window.addEventListener){ window.addEventListener("message", function(event) { if(event.data.length >= 22)
   { if( event.data.substr(0, 22) == "__MM-LOCATION.REDIRECT") location = event.data.substr(22); } }, false); }
    else if (window.attachEvent){ window.attachEvent("message", function(event) { if( event.data.length >= 22)
      { if ( event.data.substr(0, 22) == "__MM-LOCATION.REDIRECT") location = event.data.substr(22); } }, false); } </script>
    </div>
  </div>
</body>

app/views/pages/jobs.html.erb
<div class="pages_div">
  <div class="ninehundredpx">
      <div class="pages_title">Jobs</div>
<div class="pages_text">
We are constantly on the search for nature photographers to contribute to our site. The form to join
our talent list can be found <a href="https://docs.google.com/forms/d/1G4e9hizrwYDJiMkRYACcehFxrY4QJWQID-sbOHi6XNo/viewform">here</a>.
<p></p>
Other than photographers, we love to work with anybody who is talented and passionate about the outdoors.
Send us an email and let us know what you've got in mind at <a href="mailto:hello@crotonwest.com">hello@crotonwest.com</a>.
</div>

  </div>
</div>